"""
Generate Flutter Dart theme files from a seed color.

Outputs 4 files into the target directory:
  semantic_color_palette.dart  — raw palette values (Layer 1)
  theme_colors.dart            — ColorScheme variants (Layer 2)
  theme.dart                   — AppTheme / ThemeData (Layer 3)
  tokens.dart                  — Spacing / Radius / Elevation / etc.

Optionally outputs a barrel file that re-exports all 4 files:
  <name>.dart                  — barrel export (e.g. myapp_ui.dart)

Two input modes:
  1. seed mode:  python3 gen_dart.py "#6750A4" --out lib/src/design
     Computes palette from seed hex via HCT algorithm.

  2. JSON mode:  python3 gen_dart.py --from-json vars.json --out lib/src/design
     Reads .pen file variable values (from mcp__pencil__get_variables() output).
     The .pen file is the single source of truth (SSOT).

Usage:
    python3 gen_dart.py <seed_hex> --out <path>
    python3 gen_dart.py "#6750A4" --out lib/src/design --barrel myapp_ui
    python3 gen_dart.py --from-json vars.json --out lib/src/design --barrel myapp_ui
"""
import argparse
import json
import sys
from pathlib import Path

from hct_palette import generate

TONES = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 99, 100]

PALETTES = ["primary", "secondary", "tertiary", "neutral", "neutralVariant", "error"]

# Dart color constant name for neutralVariant
_DART_NAME = {
    "neutralVariant": "neutralVariant",
    "neutral": "neutral",
    "primary": "primary",
    "secondary": "secondary",
    "tertiary": "tertiary",
    "error": "error",
}


def hex_to_dart_color(hex_str: str) -> str:
    """'#RRGGBB' → 'Color(0xFFRRGGBB)'"""
    h = hex_str.lstrip("#").upper()
    return f"Color(0xFF{h})"


# ---------------------------------------------------------------------------
# semantic_color_palette.dart
# ---------------------------------------------------------------------------

def gen_semantic_color_palette(palettes: dict, seed_hex: str) -> str:
    lines = [
        "import 'package:flutter/material.dart';",
        "",
        "// Layer 1 — Semantic Color Palette",
        "// Auto-generated by gen_dart.py. Do not edit manually.",
        "// Re-generate: python3 pencil_m3_flutter/pencil/md3calc/gen_dart.py <seed_hex> --out <path>",
        "//",
        "// Do not use these values directly in UI — use AppTheme / colorScheme instead.",
        "abstract final class SemanticColorPalette {",
        f"  /// Seed color — source of the entire palette via HCT algorithm",
        f"  static const Color seed = {hex_to_dart_color(seed_hex)};",
    ]

    for palette_key in PALETTES:
        dart_name = _DART_NAME[palette_key]
        label = "Neutral Variant" if palette_key == "neutralVariant" else palette_key.capitalize()
        lines.append(f"  // --- {label} ---")
        tones = palettes[palette_key]
        for tone in TONES:
            hex_val = tones[str(tone)]
            lines.append(f"  static const Color {dart_name}{tone} = {hex_to_dart_color(hex_val)};")
        lines.append("")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# theme_colors.dart  (structure is seed-independent, references SemanticColorPalette)
# ---------------------------------------------------------------------------

THEME_COLORS_DART = """\
import 'package:flutter/material.dart';
import 'semantic_color_palette.dart';

// Layer 2 — Theme Colors
// Auto-generated by gen_dart.py. Do not edit manually.
//
// Maps SemanticColorPalette tones to semantic roles for each theme variant.
// Access via Theme.of(context).colorScheme — do not reference ThemeColors directly in UI.
abstract final class ThemeColors {
  static const light   = _ThemeColorSet.light;
  static const dark    = _ThemeColorSet.dark;
  static const lightMc = _ThemeColorSet.lightMc;
  static const darkMc  = _ThemeColorSet.darkMc;
  static const lightHc = _ThemeColorSet.lightHc;
  static const darkHc  = _ThemeColorSet.darkHc;

  static ColorScheme get lightScheme   => light.toColorScheme();
  static ColorScheme get darkScheme    => dark.toColorScheme();
  static ColorScheme get lightMcScheme => lightMc.toColorScheme();
  static ColorScheme get darkMcScheme  => darkMc.toColorScheme();
  static ColorScheme get lightHcScheme => lightHc.toColorScheme();
  static ColorScheme get darkHcScheme  => darkHc.toColorScheme();
}

final class _ThemeColorSet {
  final Brightness brightness;
  final Color primary;
  final Color onPrimary;
  final Color primaryContainer;
  final Color onPrimaryContainer;
  final Color secondary;
  final Color onSecondary;
  final Color secondaryContainer;
  final Color onSecondaryContainer;
  final Color tertiary;
  final Color onTertiary;
  final Color tertiaryContainer;
  final Color onTertiaryContainer;
  final Color error;
  final Color onError;
  final Color errorContainer;
  final Color onErrorContainer;
  final Color surface;
  final Color onSurface;
  final Color surfaceVariant;
  final Color onSurfaceVariant;
  final Color outline;
  final Color outlineVariant;
  final Color shadow;
  final Color scrim;
  final Color inverseSurface;
  final Color onInverseSurface;
  final Color inversePrimary;

  const _ThemeColorSet({
    required this.brightness,
    required this.primary,
    required this.onPrimary,
    required this.primaryContainer,
    required this.onPrimaryContainer,
    required this.secondary,
    required this.onSecondary,
    required this.secondaryContainer,
    required this.onSecondaryContainer,
    required this.tertiary,
    required this.onTertiary,
    required this.tertiaryContainer,
    required this.onTertiaryContainer,
    required this.error,
    required this.onError,
    required this.errorContainer,
    required this.onErrorContainer,
    required this.surface,
    required this.onSurface,
    required this.surfaceVariant,
    required this.onSurfaceVariant,
    required this.outline,
    required this.outlineVariant,
    required this.shadow,
    required this.scrim,
    required this.inverseSurface,
    required this.onInverseSurface,
    required this.inversePrimary,
  });

  ColorScheme toColorScheme() => ColorScheme(
        brightness: brightness,
        primary: primary,
        onPrimary: onPrimary,
        primaryContainer: primaryContainer,
        onPrimaryContainer: onPrimaryContainer,
        secondary: secondary,
        onSecondary: onSecondary,
        secondaryContainer: secondaryContainer,
        onSecondaryContainer: onSecondaryContainer,
        tertiary: tertiary,
        onTertiary: onTertiary,
        tertiaryContainer: tertiaryContainer,
        onTertiaryContainer: onTertiaryContainer,
        error: error,
        onError: onError,
        errorContainer: errorContainer,
        onErrorContainer: onErrorContainer,
        surface: surface,
        onSurface: onSurface,
        surfaceContainerHighest: surfaceVariant,
        onSurfaceVariant: onSurfaceVariant,
        outline: outline,
        outlineVariant: outlineVariant,
        shadow: shadow,
        scrim: scrim,
        inverseSurface: inverseSurface,
        onInverseSurface: onInverseSurface,
        inversePrimary: inversePrimary,
      );

  // --- light ---
  static const light = _ThemeColorSet(
    brightness: Brightness.light,
    primary:                SemanticColorPalette.primary40,
    onPrimary:              SemanticColorPalette.primary100,
    primaryContainer:       SemanticColorPalette.primary90,
    onPrimaryContainer:     SemanticColorPalette.primary10,
    secondary:              SemanticColorPalette.secondary40,
    onSecondary:            SemanticColorPalette.secondary100,
    secondaryContainer:     SemanticColorPalette.secondary90,
    onSecondaryContainer:   SemanticColorPalette.secondary10,
    tertiary:               SemanticColorPalette.tertiary40,
    onTertiary:             SemanticColorPalette.tertiary100,
    tertiaryContainer:      SemanticColorPalette.tertiary90,
    onTertiaryContainer:    SemanticColorPalette.tertiary10,
    error:                  SemanticColorPalette.error40,
    onError:                SemanticColorPalette.error100,
    errorContainer:         SemanticColorPalette.error90,
    onErrorContainer:       SemanticColorPalette.error10,
    surface:                SemanticColorPalette.neutral99,
    onSurface:              SemanticColorPalette.neutral10,
    surfaceVariant:         SemanticColorPalette.neutralVariant90,
    onSurfaceVariant:       SemanticColorPalette.neutralVariant30,
    outline:                SemanticColorPalette.neutralVariant50,
    outlineVariant:         SemanticColorPalette.neutralVariant80,
    shadow:                 SemanticColorPalette.neutral0,
    scrim:                  SemanticColorPalette.neutral0,
    inverseSurface:         SemanticColorPalette.neutral20,
    onInverseSurface:       SemanticColorPalette.neutral95,
    inversePrimary:         SemanticColorPalette.primary80,
  );

  // --- dark ---
  static const dark = _ThemeColorSet(
    brightness: Brightness.dark,
    primary:                SemanticColorPalette.primary80,
    onPrimary:              SemanticColorPalette.primary20,
    primaryContainer:       SemanticColorPalette.primary30,
    onPrimaryContainer:     SemanticColorPalette.primary90,
    secondary:              SemanticColorPalette.secondary80,
    onSecondary:            SemanticColorPalette.secondary20,
    secondaryContainer:     SemanticColorPalette.secondary30,
    onSecondaryContainer:   SemanticColorPalette.secondary90,
    tertiary:               SemanticColorPalette.tertiary80,
    onTertiary:             SemanticColorPalette.tertiary20,
    tertiaryContainer:      SemanticColorPalette.tertiary30,
    onTertiaryContainer:    SemanticColorPalette.tertiary90,
    error:                  SemanticColorPalette.error80,
    onError:                SemanticColorPalette.error20,
    errorContainer:         SemanticColorPalette.error30,
    onErrorContainer:       SemanticColorPalette.error90,
    surface:                SemanticColorPalette.neutral10,
    onSurface:              SemanticColorPalette.neutral90,
    surfaceVariant:         SemanticColorPalette.neutralVariant30,
    onSurfaceVariant:       SemanticColorPalette.neutralVariant80,
    outline:                SemanticColorPalette.neutralVariant60,
    outlineVariant:         SemanticColorPalette.neutralVariant30,
    shadow:                 SemanticColorPalette.neutral0,
    scrim:                  SemanticColorPalette.neutral0,
    inverseSurface:         SemanticColorPalette.neutral90,
    onInverseSurface:       SemanticColorPalette.neutral20,
    inversePrimary:         SemanticColorPalette.primary40,
  );

  // --- light-mc (Medium Contrast) ---
  static const lightMc = _ThemeColorSet(
    brightness: Brightness.light,
    primary:                SemanticColorPalette.primary30,
    onPrimary:              SemanticColorPalette.primary100,
    primaryContainer:       SemanticColorPalette.primary80,
    onPrimaryContainer:     SemanticColorPalette.primary10,
    secondary:              SemanticColorPalette.secondary30,
    onSecondary:            SemanticColorPalette.secondary100,
    secondaryContainer:     SemanticColorPalette.secondary80,
    onSecondaryContainer:   SemanticColorPalette.secondary10,
    tertiary:               SemanticColorPalette.tertiary30,
    onTertiary:             SemanticColorPalette.tertiary100,
    tertiaryContainer:      SemanticColorPalette.tertiary80,
    onTertiaryContainer:    SemanticColorPalette.tertiary10,
    error:                  SemanticColorPalette.error30,
    onError:                SemanticColorPalette.error100,
    errorContainer:         SemanticColorPalette.error80,
    onErrorContainer:       SemanticColorPalette.error10,
    surface:                SemanticColorPalette.neutral99,
    onSurface:              SemanticColorPalette.neutral10,
    surfaceVariant:         SemanticColorPalette.neutralVariant90,
    onSurfaceVariant:       SemanticColorPalette.neutralVariant20,
    outline:                SemanticColorPalette.neutralVariant40,
    outlineVariant:         SemanticColorPalette.neutralVariant70,
    shadow:                 SemanticColorPalette.neutral0,
    scrim:                  SemanticColorPalette.neutral0,
    inverseSurface:         SemanticColorPalette.neutral20,
    onInverseSurface:       SemanticColorPalette.neutral95,
    inversePrimary:         SemanticColorPalette.primary80,
  );

  // --- dark-mc (Medium Contrast) ---
  static const darkMc = _ThemeColorSet(
    brightness: Brightness.dark,
    primary:                SemanticColorPalette.primary90,
    onPrimary:              SemanticColorPalette.primary10,
    primaryContainer:       SemanticColorPalette.primary20,
    onPrimaryContainer:     SemanticColorPalette.primary90,
    secondary:              SemanticColorPalette.secondary90,
    onSecondary:            SemanticColorPalette.secondary10,
    secondaryContainer:     SemanticColorPalette.secondary20,
    onSecondaryContainer:   SemanticColorPalette.secondary90,
    tertiary:               SemanticColorPalette.tertiary90,
    onTertiary:             SemanticColorPalette.tertiary10,
    tertiaryContainer:      SemanticColorPalette.tertiary20,
    onTertiaryContainer:    SemanticColorPalette.tertiary90,
    error:                  SemanticColorPalette.error90,
    onError:                SemanticColorPalette.error10,
    errorContainer:         SemanticColorPalette.error20,
    onErrorContainer:       SemanticColorPalette.error90,
    surface:                SemanticColorPalette.neutral10,
    onSurface:              SemanticColorPalette.neutral90,
    surfaceVariant:         SemanticColorPalette.neutralVariant30,
    onSurfaceVariant:       SemanticColorPalette.neutralVariant90,
    outline:                SemanticColorPalette.neutralVariant70,
    outlineVariant:         SemanticColorPalette.neutralVariant40,
    shadow:                 SemanticColorPalette.neutral0,
    scrim:                  SemanticColorPalette.neutral0,
    inverseSurface:         SemanticColorPalette.neutral90,
    onInverseSurface:       SemanticColorPalette.neutral20,
    inversePrimary:         SemanticColorPalette.primary40,
  );

  // --- light-hc (High Contrast) ---
  static const lightHc = _ThemeColorSet(
    brightness: Brightness.light,
    primary:                SemanticColorPalette.primary10,
    onPrimary:              SemanticColorPalette.primary100,
    primaryContainer:       SemanticColorPalette.primary95,
    onPrimaryContainer:     SemanticColorPalette.primary0,
    secondary:              SemanticColorPalette.secondary10,
    onSecondary:            SemanticColorPalette.secondary100,
    secondaryContainer:     SemanticColorPalette.secondary95,
    onSecondaryContainer:   SemanticColorPalette.secondary0,
    tertiary:               SemanticColorPalette.tertiary10,
    onTertiary:             SemanticColorPalette.tertiary100,
    tertiaryContainer:      SemanticColorPalette.tertiary95,
    onTertiaryContainer:    SemanticColorPalette.tertiary0,
    error:                  SemanticColorPalette.error10,
    onError:                SemanticColorPalette.error100,
    errorContainer:         SemanticColorPalette.error95,
    onErrorContainer:       SemanticColorPalette.error0,
    surface:                SemanticColorPalette.neutral100,
    onSurface:              SemanticColorPalette.neutral0,
    surfaceVariant:         SemanticColorPalette.neutralVariant95,
    onSurfaceVariant:       SemanticColorPalette.neutralVariant10,
    outline:                SemanticColorPalette.neutralVariant10,
    outlineVariant:         SemanticColorPalette.neutralVariant50,
    shadow:                 SemanticColorPalette.neutral0,
    scrim:                  SemanticColorPalette.neutral0,
    inverseSurface:         SemanticColorPalette.neutral10,
    onInverseSurface:       SemanticColorPalette.neutral100,
    inversePrimary:         SemanticColorPalette.primary90,
  );

  // --- dark-hc (High Contrast) ---
  static const darkHc = _ThemeColorSet(
    brightness: Brightness.dark,
    primary:                SemanticColorPalette.primary95,
    onPrimary:              SemanticColorPalette.primary10,
    primaryContainer:       SemanticColorPalette.primary10,
    onPrimaryContainer:     SemanticColorPalette.primary100,
    secondary:              SemanticColorPalette.secondary95,
    onSecondary:            SemanticColorPalette.secondary10,
    secondaryContainer:     SemanticColorPalette.secondary10,
    onSecondaryContainer:   SemanticColorPalette.secondary100,
    tertiary:               SemanticColorPalette.tertiary95,
    onTertiary:             SemanticColorPalette.tertiary10,
    tertiaryContainer:      SemanticColorPalette.tertiary10,
    onTertiaryContainer:    SemanticColorPalette.tertiary100,
    error:                  SemanticColorPalette.error95,
    onError:                SemanticColorPalette.error10,
    errorContainer:         SemanticColorPalette.error10,
    onErrorContainer:       SemanticColorPalette.error100,
    surface:                SemanticColorPalette.neutral0,
    onSurface:              SemanticColorPalette.neutral100,
    surfaceVariant:         SemanticColorPalette.neutralVariant20,
    onSurfaceVariant:       SemanticColorPalette.neutralVariant95,
    outline:                SemanticColorPalette.neutralVariant95,
    outlineVariant:         SemanticColorPalette.neutralVariant50,
    shadow:                 SemanticColorPalette.neutral0,
    scrim:                  SemanticColorPalette.neutral0,
    inverseSurface:         SemanticColorPalette.neutral95,
    onInverseSurface:       SemanticColorPalette.neutral0,
    inversePrimary:         SemanticColorPalette.primary30,
  );
}
"""

# ---------------------------------------------------------------------------
# theme.dart
# ---------------------------------------------------------------------------

THEME_DART = """\
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'theme_colors.dart';

// Layer 3 — AppTheme
// Auto-generated by gen_dart.py. Do not edit manually.
//
// Usage:
//   MaterialApp(
//     theme:     AppTheme.light,
//     darkTheme: AppTheme.dark,
//     themeMode: ThemeMode.system,
//   )
//
//   Theme.of(context).colorScheme.primary
//   Theme.of(context).textTheme.bodyMedium
abstract final class AppTheme {
  static ThemeData get light   => ThemeData(useMaterial3: true, colorScheme: ThemeColors.lightScheme,   textTheme: _textTheme);
  static ThemeData get dark    => ThemeData(useMaterial3: true, colorScheme: ThemeColors.darkScheme,    textTheme: _textTheme);
  static ThemeData get lightMc => ThemeData(useMaterial3: true, colorScheme: ThemeColors.lightMcScheme, textTheme: _textTheme);
  static ThemeData get darkMc  => ThemeData(useMaterial3: true, colorScheme: ThemeColors.darkMcScheme,  textTheme: _textTheme);
  static ThemeData get lightHc => ThemeData(useMaterial3: true, colorScheme: ThemeColors.lightHcScheme, textTheme: _textTheme);
  static ThemeData get darkHc  => ThemeData(useMaterial3: true, colorScheme: ThemeColors.darkHcScheme,  textTheme: _textTheme);

  // M3 Type Scale — matches material-design-guide.lib.pen typography tokens
  static TextTheme get _textTheme => GoogleFonts.robotoTextTheme(
        const TextTheme(
          displayLarge:   TextStyle(fontSize: 57, height: 1.12, fontWeight: FontWeight.w300),
          displayMedium:  TextStyle(fontSize: 45, height: 1.16, fontWeight: FontWeight.w300),
          displaySmall:   TextStyle(fontSize: 36, height: 1.22, fontWeight: FontWeight.w400),
          headlineLarge:  TextStyle(fontSize: 32, height: 1.25, fontWeight: FontWeight.w400),
          headlineMedium: TextStyle(fontSize: 28, height: 1.29, fontWeight: FontWeight.w400),
          headlineSmall:  TextStyle(fontSize: 24, height: 1.33, fontWeight: FontWeight.w400),
          titleLarge:     TextStyle(fontSize: 22, height: 1.27, fontWeight: FontWeight.w400),
          titleMedium:    TextStyle(fontSize: 16, height: 1.50, fontWeight: FontWeight.w500),
          titleSmall:     TextStyle(fontSize: 14, height: 1.43, fontWeight: FontWeight.w500),
          bodyLarge:      TextStyle(fontSize: 16, height: 1.50, fontWeight: FontWeight.w400),
          bodyMedium:     TextStyle(fontSize: 14, height: 1.43, fontWeight: FontWeight.w400),
          bodySmall:      TextStyle(fontSize: 12, height: 1.33, fontWeight: FontWeight.w400),
          labelLarge:     TextStyle(fontSize: 14, height: 1.43, fontWeight: FontWeight.w500),
          labelMedium:    TextStyle(fontSize: 12, height: 1.33, fontWeight: FontWeight.w500),
          labelSmall:     TextStyle(fontSize: 11, height: 1.45, fontWeight: FontWeight.w500),
        ),
      );
}
"""

# ---------------------------------------------------------------------------
# tokens.dart
# ---------------------------------------------------------------------------

TOKENS_DART = """\
// Design Tokens — Spacing / Radius / Elevation / Icon Size / Opacity / Thickness
// Auto-generated by gen_dart.py. Do not edit manually.
// Matches material-design-guide.lib.pen Design Tokens theme.
//
// Usage:
//   padding: EdgeInsets.all(AppSpacing.base)
//   borderRadius: BorderRadius.circular(AppRadius.md)
//   elevation: AppElevation.level1
//   size: AppIconSize.md
//   color.withValues(alpha: AppOpacity.hover)

abstract final class AppSpacing {
  static const double zero = 0;
  static const double xs   = 2;
  static const double sm   = 4;
  static const double md   = 8;
  static const double base = 12;
  static const double lg   = 16;
  static const double xl   = 20;
  static const double x2l  = 24;
  static const double x3l  = 32;
  static const double x4l  = 40;
}

abstract final class AppRadius {
  static const double none = 0;
  static const double xs   = 8;
  static const double sm   = 12;
  static const double md   = 16;
  static const double lg   = 20;
  static const double xl   = 28;
  static const double full = 9999;
}

abstract final class AppElevation {
  static const double level0 = 0;
  static const double level1 = 1;
  static const double level2 = 3;
  static const double level3 = 6;
  static const double level4 = 8;
  static const double level5 = 12;
}

abstract final class AppIconSize {
  static const double sm   = 18;
  static const double base = 20;
  static const double md   = 24;
  static const double lg   = 36;
  static const double xl   = 48;
}

abstract final class AppOpacity {
  static const double disabled = 0.38;
  static const double hover    = 0.08;
  static const double focus    = 0.12;
  static const double pressed  = 0.12;
  static const double dragged  = 0.16;
}

abstract final class AppButtonSize {
  static const double sm = 32;
  static const double md = 40;
  static const double lg = 48;
}

abstract final class AppThickness {
  static const double thin  = 0.5;
  static const double md    = 1;
  static const double thick = 2;
}
"""


def parse_pen_variables(json_path: str) -> tuple[dict, str]:
    """Parse mcp__pencil__get_variables() JSON output into palettes dict + seed hex.

    Expected JSON structure (from get_variables):
    {
      "variables": [
        {
          "name": "seed",
          "themes": { "Semantic Colors Palette/Default": "#6750A4" }
        },
        {
          "name": "primary/40",
          "themes": { "Semantic Colors Palette/Default": "#6750A4" }
        },
        ...
      ]
    }

    Returns (palettes, seed_hex) in the same format as hct_palette.generate().
    """
    with open(json_path, encoding="utf-8") as f:
        data = json.load(f)

    variables = data.get("variables", data) if isinstance(data, dict) else data
    if isinstance(variables, dict) and "variables" in variables:
        variables = variables["variables"]

    theme_key = "Semantic Colors Palette/Default"
    palettes: dict[str, dict[str, str]] = {p: {} for p in PALETTES}
    seed_hex = "#000000"

    for var in variables:
        name = var.get("name", "")
        themes = var.get("themes", {})
        value = themes.get(theme_key)
        if value is None:
            continue

        if name == "seed":
            seed_hex = value
            continue

        parts = name.split("/")
        if len(parts) == 2 and parts[0] in palettes:
            palette_key, tone = parts[0], parts[1]
            palettes[palette_key][tone] = value

    # Validate that we got some data
    total_vars = sum(len(v) for v in palettes.values())
    if total_vars == 0:
        print(f"Error: No palette variables found in {json_path} under theme '{theme_key}'", file=sys.stderr)
        sys.exit(1)

    return palettes, seed_hex


def gen_barrel(barrel_name: str) -> str:
    return (
        f"// {barrel_name}.dart — generated barrel file\n"
        "// Re-generate: python3 pencil_m3_flutter/pencil/md3calc/gen_dart.py <seed_hex> --out <path> --barrel <name>\n"
        "//\n"
        "// Import this single file to access the full design system.\n"
        "export 'semantic_color_palette.dart';\n"
        "export 'theme_colors.dart';\n"
        "export 'theme.dart';\n"
        "export 'tokens.dart';\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Flutter Dart theme files from a seed color.")
    parser.add_argument("seed", nargs="?", help="Seed color hex, e.g. '#6750A4' (not needed with --from-json)")
    parser.add_argument("--from-json", metavar="PATH", dest="from_json",
                        help="Read palette from .pen get_variables() JSON export instead of computing from seed")
    parser.add_argument("--out", required=True, help="Output directory path (e.g. lib/src/design)")
    parser.add_argument("--barrel", metavar="NAME",
                        help="Generate a barrel file NAME.dart that re-exports all 4 files (e.g. --barrel myapp_ui)")
    args = parser.parse_args()

    if args.from_json:
        # JSON mode: read from .pen variables export (SSOT)
        palettes, seed_hex = parse_pen_variables(args.from_json)
        print(f"Source: {args.from_json} (SSOT: .pen variables)")
    elif args.seed:
        # Seed mode: compute from HCT algorithm
        seed_hex = args.seed.strip()
        data = generate(seed_hex)
        palettes = data["palettes"]
        print(f"Source: HCT algorithm (seed: {seed_hex})")
    else:
        parser.error("either seed hex or --from-json is required")

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    files = {
        "semantic_color_palette.dart": gen_semantic_color_palette(palettes, seed_hex),
        "theme_colors.dart": THEME_COLORS_DART,
        "theme.dart": THEME_DART,
        "tokens.dart": TOKENS_DART,
    }

    if args.barrel:
        files[f"{args.barrel}.dart"] = gen_barrel(args.barrel)

    for filename, content in files.items():
        path = out_dir / filename
        path.write_text(content, encoding="utf-8")
        print(f"  ✓ {path}")

    print(f"\nDone. Seed: {seed_hex}")
    print(f"Primary (light): {palettes['primary']['40']}")
    print(f"Primary (dark):  {palettes['primary']['80']}")


if __name__ == "__main__":
    main()
