// AUTO-GENERATED by plot_mcp/ts_codegen.py — DO NOT EDIT.
// Regenerate: uv run python -m plot_mcp.ts_codegen
// SSOT: plot_mcp Pydantic models (BaseNodeFields + the SketchNode union).
// Wire shape only — the per-kind domain *class* (fromJson/toJson) is hand-written.

import type { Shape } from "../types";

export interface BaseFieldsJson {
  id: string;
  label: string;
  x: number;
  y: number;
  width: number;
  height: number;
  color: string;
  shape: Shape;
  icon: string | null;
  collapsed: boolean;
  is_root: boolean;
  details_path: string | null;
  owner: string | null;
  version: string;
  publish_baseline?: unknown;
}

export interface ProjectJson extends BaseFieldsJson {
  kind: "project";
}

export interface MissionJson extends BaseFieldsJson {
  kind: "mission";
  statement: string;
  body: string;
}

export interface CoreValueJson extends BaseFieldsJson {
  kind: "core_value";
  definition: string;
  body: string;
}

export interface IdentityJson extends BaseFieldsJson {
  kind: "identity";
  description: string;
  body: string;
  status: "manual" | "derived" | "confirmed";
  provenance: string[];
}

export interface ActorJson extends BaseFieldsJson {
  kind: "actor";
  side: "operator" | "user" | null;
  body: string;
}

export interface ActorRefJson extends BaseFieldsJson {
  kind: "actor_ref";
  ref_actor_id: string | null;
  side: "operator" | "user" | null;
}

export interface ServiceJson extends BaseFieldsJson {
  kind: "service";
  problem: string;
  value_created: string;
  ref_actor_ids: string[];
  ref_value_ids: string[];
  ref_identity_ids: string[];
}

export interface FeatureJson extends BaseFieldsJson {
  kind: "feature";
  proposed: string;
}

export interface CategoryJson extends BaseFieldsJson {
  kind: "category";
  theme: string;
  body: string;
}

export interface MissionRefJson extends BaseFieldsJson {
  kind: "mission_ref";
  ref_mission_id: string | null;
  notes_in_context: string;
}

export interface ValueRefJson extends BaseFieldsJson {
  kind: "value_ref";
  ref_value_id: string | null;
  notes_in_context: string;
}

export interface IdentityRefJson extends BaseFieldsJson {
  kind: "identity_ref";
  ref_identity_id: string | null;
  notes_in_context: string;
}

export interface MetricJson extends BaseFieldsJson {
  kind: "metric";
  target: string;
  measurement: string;
  body: string;
}

export interface StepJson extends BaseFieldsJson {
  kind: "step";
  order: number | null;
  outcome: string;
  body: string;
  polarity: "positive" | "negative" | "neutral";
}

export interface DecisionJson extends BaseFieldsJson {
  kind: "decision";
  body: string;
}

export interface NoteJson extends BaseFieldsJson {
  kind: "note";
  body: string;
}

export interface RuleJson extends BaseFieldsJson {
  kind: "rule";
  policy: string;
  enforcement: string;
  actor_permissions: Record<string, string>;
  body: string;
}

export interface ContentJson extends BaseFieldsJson {
  kind: "content";
  format: string;
  producer_actor_id: string | null;
  consumer_actor_id: string | null;
  body: string;
}
